/* eslint-disable @next/next/no-page-custom-font */
import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import React from 'react';

export default function App({ Component, pageProps, router }: AppProps): JSX.Element {
	return <>
		<Head>
			<title>MyTop - наш лучший топ</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
			<meta property="og:url" content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}/>
			<meta property="og:locale" content="ru-RU"/>
		</Head>
		<Component {...pageProps} />
	</>;
}
